use derive_getters::Getters;

use crate::{
    Text,
    messages::{Message, MessageAdder, Messages},
    simulation::Simulation,
};

/// A report is the top-level data structure for responses when checking programs
#[derive(Debug, PartialEq, PartialOrd, Clone, Getters)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "kebab-case"))]
pub struct Report {
    /// Messages for the whole report
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "crate::is_default")
    )]
    messages: Messages<Report>,
    form: Option<Formality>,
    simulation: Option<Simulation>,
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "crate::is_default")
    )]
    contains_extra_messages: bool,
}
impl Report {
    /// Adds extra messages by computing them from structured information.
    /// Those are good for humans to read but the user good also get information
    /// by explicitly showing information for the structures.
    pub fn add_extra_messages(&mut self) -> bool {
        if self.contains_extra_messages {
            return false;
        }

        if let Some(sim) = self.simulation.as_mut() {
            sim.add_extra_messages(&mut self.messages);
        }
        if let Some(form) = self.form.as_mut() {
            if let Err(ambiguity) = form.initial_block() {
                match ambiguity {
                    InitialBlockAmbiguity::No => self.messages.notify(NO_INITIAL_BLOCK),
                    InitialBlockAmbiguity::Multiple => self.messages.notify(MANY_INITIAL_BLOCKS),
                }
            }
            if *form.cyclic_graph() {
                self.messages.notify(PROGRAM_GRAPH_CYCLIC);
            }
            if let Some(exceeded) = form.max_blocks_exceeded() {
                self.messages.notify(Message::warning(format!("Ihr Programm benutzt sehr viele Blöcke. Die Aufgabensteller sehen maximal {} vor, Ihr Programm nutzt jedoch {}. Die Tutoren werden dafür sehr wahrscheinlich keinen Punktabzug geben, es zeigt aber, dass Sie Ihr Programm noch anpassen sollten, da die Begrenzungen eigentlich sehr großzügig gesetzt sind. (Ich zähle auch die Blöcke, die in der Datei sind und nicht benutzt werden)", exceeded.allowed, exceeded.used)));
                if let Some(msg) = exceeded.msg() {
                    // Change level from Formality to Report
                    // Exercise creators need to ensure that this message isn't redundant
                    self.messages.notify(msg.clone().change_level());
                }
            }
        }

        self.contains_extra_messages = true;
        true
    }
}

#[derive(Debug, PartialEq, PartialOrd, Clone, Getters)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "kebab-case"))]
pub struct Formality {
    #[cfg_attr(feature = "utoipa", schema(value_type= SchemaResult<String, InitialBlockAmbiguity>))]
    initial_block: Result<smodel::Id, InitialBlockAmbiguity>,
    /// if the block pointers form a cycle (true), the file is malicious or at least invalid
    cyclic_graph: bool,
    max_blocks_exceeded: Option<MaxBlocksExceeded>,
}

#[derive(Debug, PartialEq, PartialOrd, Clone)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum SchemaResult<T, E> {
    Ok(T),
    Err(E),
}

#[derive(Debug, PartialEq, PartialOrd, Clone, Getters)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "kebab-case"))]
pub struct MaxBlocksExceeded {
    used: usize,
    allowed: usize,
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "crate::is_default")
    )]
    /// Optional additional message.
    /// On [Report::add_extra_messages], this will be added if present,
    /// but in such cases also an autogenerated message with [MaxBlocksExceeded::used]
    /// and [MaxBlocksExceeded::allowed] in it will be added, so this message
    /// doesn't have to repeat it and shouln't look redundant to a user
    msg: Option<Message<Formality>>,
}
impl MaxBlocksExceeded {
    pub fn new_with_msg(used: usize, allowed: usize, msg: impl Into<Text>) -> Self {
        Self {
            used,
            allowed,
            msg: Some(Message::warning(msg.into().0)),
        }
    }
    pub fn new(used: usize, allowed: usize) -> Self {
        Self {
            used,
            allowed,
            msg: None,
        }
    }
}

impl Formality {
    pub fn new(
        initial_block: Result<svalue::ARc<str>, InitialBlockAmbiguity>,
        cyclic_graph: bool,
        max_blocks_exceeded: Result<(), MaxBlocksExceeded>,
    ) -> Self {
        Self {
            initial_block,
            cyclic_graph,
            max_blocks_exceeded: max_blocks_exceeded.err(),
        }
    }
}

#[derive(Debug, PartialEq, PartialOrd, Clone)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "kebab-case"))]
pub enum InitialBlockAmbiguity {
    No,
    Multiple,
}

impl Report {
    pub fn new(form: Option<Formality>, simulation: Option<Simulation>) -> Self {
        Self {
            messages: Default::default(),
            form,
            simulation,
            contains_extra_messages: false,
        }
    }
}

const NO_INITIAL_BLOCK: Message<Report> = Message::cerror(
    "Ihr Programm enthält keinen Startblock (wahrscheinlich die grüne Flagge), deswegen weiß ich leider nicht, wo ich beginnen soll, und kann das Programm nicht ausführen. Bitte versehen Sie Ihr Programm mit einem Startblock.",
);
const MANY_INITIAL_BLOCKS: Message<Report> = Message::cerror(
    "Ihr Programm enthält mehr als einen infragekommenden Startblock (mehrere grüne Flaggen?), deswegen weiß ich nicht, welche ich wehlen soll, und kann das Programm nicht ausführen. Bitte entfernen Sie alle Startblöcke, bis auf einen.",
);

const PROGRAM_GRAPH_CYCLIC: Message<Report> = Message::cerror(
    "Irgendetwas stimmt nicht mit der Datei, die sie abgegeben haben. Sie enthält einen Zyklus. Ich will Ihnen nichts unterstellen, aber das erwarte ich eigentlich nur bei bösartigen und/oder KI-generierten Abgaben. Bitte melden Sie sich bei den Aufgabenstellern, damit wir dieses Problem beheben können.",
);
